# Generated by Django 5.1.1 on 2025-01-25 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0018_dividenddetailedholding_budget_year_and_more'),
        ('users', '0007_customuser_token_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins', to='stocks.listedcompany'),
        ),
    ]
