# Generated by Django 5.1.1 on 2025-01-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='company_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
