# Generated by Django 5.1.1 on 2024-12-24 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_dailyclosingprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disclosure_type', models.CharField(choices=[('Financial Statement', 'Financial Statement'), ('Annual Report', 'Annual Report'), ('Material Event', 'Material Event'), ('Quarterly Report', 'Quarterly Report')], help_text="Type of disclosure (e.g., 'Financial Statement', 'Annual Report').", max_length=50)),
                ('year', models.PositiveIntegerField(help_text='Fiscal or reporting year for this disclosure.')),
                ('file', models.FileField(help_text='File containing disclosure document.', upload_to='disclosures/')),
                ('description', models.TextField(blank=True, help_text='Optional description or summary of the disclosure.', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp indicating when this disclosure was uploaded.')),
                ('company', models.ForeignKey(help_text='Company to which this disclosure belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='disclosures', to='stocks.listedcompany')),
            ],
            options={
                'verbose_name': 'Disclosure',
                'verbose_name_plural': 'Disclosures',
                'ordering': ['-year', '-uploaded_at'],
            },
        ),
    ]
