# Generated by Django 5.1.1 on 2024-12-24 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_disclosure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disclosure',
            old_name='disclosure_type',
            new_name='type',
        ),
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_activities', to='stocks.trade')),
            ],
        ),
    ]
