# Generated by Django 5.1.1 on 2025-01-08 13:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_rename_disclosure_type_disclosure_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('OrderCreated', 'Order Created'), ('TradeExecuted', 'Trade Executed'), ('OrderCancelled', 'Order Cancelled'), ('OrderPartiallyFilled', 'Order Partially Filled'), ('TransactionFeeDeducted', 'Transaction Fee Deducted')], max_length=50)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddIndex(
            model_name='orders',
            index=models.Index(fields=['status'], name='stocks_orde_status_9e6165_idx'),
        ),
        migrations.AddIndex(
            model_name='orders',
            index=models.Index(fields=['stock', 'action', 'price', 'status'], name='stocks_orde_stock_i_4038e0_idx'),
        ),
        migrations.AddIndex(
            model_name='orders',
            index=models.Index(fields=['created_at'], name='stocks_orde_created_87cb33_idx'),
        ),
        migrations.AddField(
            model_name='transactionaudittrail',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.orders'),
        ),
        migrations.AddField(
            model_name='transactionaudittrail',
            name='trade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.trade'),
        ),
    ]
