# Generated by Django 5.1.1 on 2025-01-08 14:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_transactionaudittrail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='transaction_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='trade',
            name='transaction_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
