# Generated by Django 5.1.1 on 2025-01-08 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_orders_transaction_fee_trade_transaction_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionaudittrail',
            name='created_at',
        ),
        migrations.AddField(
            model_name='trade',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='stocks.orders'),
        ),
        migrations.AddField(
            model_name='transactionaudittrail',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionaudittrail',
            name='details',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='transactionaudittrail',
            name='event_type',
            field=models.CharField(choices=[('OrderCreated', 'Order Created'), ('TradeExecuted', 'Trade Executed'), ('TransactionFeeDeducted', 'Transaction Fee Deducted'), ('Direct Purchase', 'Direct Purchase')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transactionaudittrail',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.orders'),
        ),
        migrations.AlterField(
            model_name='transactionaudittrail',
            name='trade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.trade'),
        ),
    ]
