# Generated by Django 5.1.1 on 2025-01-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_remove_transactionaudittrail_created_at_trade_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disclosure',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description or summary.', null=True),
        ),
        migrations.AlterField(
            model_name='disclosure',
            name='type',
            field=models.CharField(choices=[('Financial Statement', 'Financial Statement'), ('Annual Report', 'Annual Report'), ('Material Event', 'Material Event'), ('Quarterly Report', 'Quarterly Report')], help_text="Type of disclosure, e.g. 'Financial Statement', 'Annual Report'.", max_length=50),
        ),
        migrations.AlterField(
            model_name='disclosure',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp of upload.'),
        ),
        migrations.AlterField(
            model_name='disclosure',
            name='year',
            field=models.PositiveIntegerField(help_text='Fiscal/reporting year for this disclosure.'),
        ),
    ]
