# Generated by Django 5.1.1 on 2025-01-17 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0014_alter_disclosure_description_alter_disclosure_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DividendDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dividend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='stocks.dividend')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividend_distributions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
