# Generated by Django 5.1.1 on 2025-01-21 17:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0015_dividenddistribution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DividendDetailedHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('stock_symbol', models.CharField(max_length=10)),
                ('order_type', models.CharField(blank=True, max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity', models.IntegerField()),
                ('transaction_fee', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_buying_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('weighted_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dividend_eligible', models.CharField(max_length=5)),
                ('trade_time', models.DateTimeField()),
                ('ratio_at_creation', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dividend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_holdings', to='stocks.dividend')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividend_holdings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
