# Generated by Django 5.1.1 on 2025-01-21 18:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0016_dividenddetailedholding'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividenddetailedholding',
            name='paid_dividend',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='dividend',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Disbursed', 'Disbursed')], default='Pending', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='dividend',
            unique_together={('company', 'budget_year')},
        ),
    ]
