# Generated by Django 5.1.1 on 2025-01-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0017_dividenddetailedholding_paid_dividend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividenddetailedholding',
            name='budget_year',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='dividenddetailedholding',
            name='company_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
